name: Discord smoke test
on:
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content":"✅ Discord webhook OK (smoke test)."}' \
            "$DISCORD_WEBHOOK"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
